# Generated by Django 3.1.1 on 2020-11-18 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='unknown', max_length=100)),
                ('news_url', models.CharField(default='unknown', max_length=100)),
                ('category', models.CharField(default='unknown', max_length=30)),
                ('media', models.CharField(default='unknown', max_length=50)),
                ('tags', models.CharField(default='unknown', max_length=100)),
                ('title', models.CharField(default='unknown', max_length=60)),
                ('news_id', models.CharField(db_index=True, default='unknown', max_length=50)),
                ('pub_date', models.CharField(default='unknown', max_length=100)),
                ('content', models.CharField(default='unknown', max_length=10000)),
                ('summary', models.CharField(default='unknown', max_length=500)),
                ('img', models.CharField(default='nothing', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100)),
                ('create_time', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='unknown', max_length=20)),
                ('password', models.CharField(default='unknown', max_length=20)),
                ('email', models.CharField(default='unknown', max_length=30)),
                ('phone_number', models.CharField(default='unknown', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_record', to='backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Behavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_behavior', to='backend.user')),
            ],
        ),
    ]
