# Generated by Django 3.1.1 on 2020-10-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
