# Generated by Django 3.1.1 on 2020-10-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201014_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
