# Generated by Django 3.1.1 on 2020-10-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_news_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(default='unknown', max_length=10000),
        ),
        migrations.AlterField(
            model_name='news',
            name='media',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_url',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='summary',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='unknown', max_length=60),
        ),
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
