# Generated by Django 3.1.1 on 2020-10-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201016_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='video',
        ),
    ]
