# Generated by Django 3.1.1 on 2020-10-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_remove_news_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.CharField(default='nothing', max_length=100),
        ),
    ]
