# Generated by Django 3.1.1 on 2020-11-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_news_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_id',
            field=models.CharField(db_index=True, default='unknown', max_length=50),
        ),
    ]
