# Generated by Django 3.1.1 on 2020-11-10 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_behavior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='behavior',
            name='content',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='behavior',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_behavior', to='backend.user'),
        ),
    ]
