# Generated by Django 3.1.1 on 2020-11-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='create_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
