# Generated by Django 3.1.1 on 2020-11-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_search_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
