# Generated by Django 3.1.1 on 2020-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_auto_20201118_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='create_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
